### ISSUE TITLE
Examples site crash in IE

### ISSUE THREAD

**Issue by jornare** [justindujardin/ng2-material#150]
The sample site does not start in IE11, and IE10(emulated).
Log/Stack traces:

```
loaded app
EXCEPTION: SyntaxError: Expected ';'
   EXCEPTION: SyntaxError: Expected ';'

Potentially unhandled rejection [8] SyntaxError: Expected ';'
   at evalExpression (https://justindujardin.github.io/ng2-material/node_modules/angular2/bundles/angular2.dev.js:459:5)
   at TemplateCompiler.prototype._createViewFactoryRuntime (https://justindujardin.github.io/ng2-material/node_modules/angular2/bundles/angular2.dev.js:25033:9)
   at Anonymous function (https://justindujardin.github.io/ng2-material/node_modules/angular2/bundles/angular2.dev.js:24987:13)
   at M (https://justindujardin.github.io/ng2-material/node_modules/systemjs/dist/system-polyfills.js:4:8725)
   at H (https://justindujardin.github.io/ng2-material/node_modules/systemjs/dist/system-polyfills.js:4:8312)
   at R.prototype.when (https://justindujardin.github.io/ng2-material/node_modules/systemjs/dist/system-polyfills.js:4:12044)
   at O.prototype.run (https://justindujardin.github.io/ng2-material/node_modules/systemjs/dist/system-polyfills.js:4:13133)
   at t.prototype._drain (https://justindujardin.github.io/ng2-material/node_mod

Potentially unhandled rejection [9] SyntaxError: Expected ';'
   at evalExpression (https://justindujardin.github.io/ng2-material/node_modules/angular2/bundles/angular2.dev.js:459:5)
   at TemplateCompiler.prototype._createViewFactoryRuntime (https://justindujardin.github.io/ng2-material/node_modules/angular2/bundles/angular2.dev.js:25033:9)
   at Anonymous function (https://justindujardin.github.io/ng2-material/node_modules/angular2/bundles/angular2.dev.js:24987:13)
   at M (https://justindujardin.github.io/ng2-material/node_modules/systemjs/dist/system-polyfills.js:4:8725)
   at H (https://justindujardin.github.io/ng2-material/node_modules/systemjs/dist/system-polyfills.js:4:8312)
   at R.prototype.when (https://justindujardin.github.io/ng2-material/node_modules/systemjs/dist/system-polyfills.js:4:12044)
   at O.prototype.run (https://justindujardin.github.io/ng2-material/node_modules/systemjs/dist/system-polyfills.js:4:13133)
   at t.prototype._drain (https://justindujardin.github.io/ng2-material/node_mod
```

**Comment by ollwenjones** [comment]
Don't have the right polyfills for those browsers?

**Comment by jornare** [comment]
I'm referring to the actual http://justindujardin.github.io/
The polyfills are there and the build is green but it breaks in the actual browser.

**Comment by lelezeus88** [comment]
Have the same issue

**Comment by justindujardin** [comment]
@ollwenjones @Gregcop1 could one of you create a PR to load the ie shims on the example site, and verify if it works?

**Comment by jornare** [comment]
I see there have been a little progress. It still fails though, but works with the debugger on. This is typical when console.log is used (since console is not an object unless the console is visible) in IE.
Solution: remove all console.log entries, or create a fake console object with a log function on it.
Example: window.console || window.console = { log: function(){}};
