### ISSUE TITLE
CSS source map file "all.css.map" is not copied to dist folder

### ISSUE THREAD

**Issue by madhukard** [justindujardin/ng2-material#8]
```
[01:58:24] 'scripts-bundle' errored after 5.44 s
[01:58:24] Error: ENOENT: no such file or directory, open '/home/travis/build/madhukard/angular2-jspm-seed/target/development/jspm/npm/ng2-material@0.1.3/dist/all.css.map'
    at Error (native)
    at Object.fs.openSync (fs.js:585:18)
    at Object.fs.readFileSync (fs.js:432:33)
    at fromSource (file:///home/travis/build/madhukard/angular2-jspm-seed/target/development/jspm/npm/clean-css@3.4.8/lib/utils/input-source-map-tracker.js:70:32)
    at InputSourceMapStore.track (file:///home/travis/build/madhukard/angular2-jspm-seed/target/development/jspm/npm/clean-css@3.4.8/lib/utils/input-source-map-tracker.js:186:91)
    at Object.whenDone (file:///home/travis/build/madhukard/angular2-jspm-seed/target/development/jspm/npm/clean-css@3.4.8/lib/clean.js:107:46)
    at processNext (file:///home/travis/build/madhukard/angular2-jspm-seed/target/development/jspm/npm/clean-css@3.4.8/lib/imports/inliner.js:85:93)
    at importFrom (file:///home/travis/build/madhukard/angular2-jspm-seed/target/development/jspm/npm/clean-css@3.4.8/lib/imports/inliner.js:67:12)
    at processNext (file:///home/travis/build/madhukard/angular2-jspm-seed/target/development/jspm/npm/clean-css@3.4.8/lib/imports/inliner.js:85:49)
    at importFrom (file:///home/travis/build/madhukard/angular2-jspm-seed/target/development/jspm/npm/clean-css@3.4.8/lib/imports/inliner.js:67:12)
    at inlineLocalResource (file:///home/travis/build/madhukard/angular2-jspm-seed/target/development/jspm/npm/clean-css@3.4.8/lib/imports/inliner.js:273:12)
    at inline (file:///home/travis/build/madhukard/angular2-jspm-seed/target/development/jspm/npm/clean-css@3.4.8/lib/imports/inliner.js:157:12)
    at importFrom (file:///home/travis/build/madhukard/angular2-jspm-seed/target/development/jspm/npm/clean-css@3.4.8/lib/imports/inliner.js:64:14)
    at processNext (file:///home/travis/build/madhukard/angular2-jspm-seed/target/development/jspm/npm/clean-css@3.4.8/lib/imports/inliner.js:85:49)
    at importFrom (file:///home/travis/build/madhukard/angular2-jspm-seed/target/development/jspm/npm/clean-css@3.4.8/lib/imports/inliner.js:67:12)
    at inlineLocalResource (file:///home/travis/build/madhukard/angular2-jspm-seed/target/development/jspm/npm/clean-css@3.4.8/lib/imports/inliner.js:273:12)
    at inline (file:///home/travis/build/madhukard/angular2-jspm-seed/target/development/jspm/npm/clean-css@3.4.8/lib/imports/inliner.js:157:12)
    at importFrom (file:///home/travis/build/madhukard/angular2-jspm-seed/target/development/jspm/npm/clean-css@3.4.8/lib/imports/inliner.js:64:14)
    at processNext (file:///home/travis/build/madhukard/angular2-jspm-seed/target/development/jspm/npm/clean-css@3.4.8/lib/imports/inliner.js:85:49)
    at importFrom (file:///home/travis/build/madhukard/angular2-jspm-seed/target/development/jspm/npm/clean-css@3.4.8/lib/imports/inliner.js:67:12)
    at inlineLocalResource (file:///home/travis/build/madhukard/angular2-jspm-seed/target/development/jspm/npm/clean-css@3.4.8/lib/imports/inliner.js:273:12)
    at inline (file:///home/travis/build/madhukard/angular2-jspm-seed/target/development/jspm/npm/clean-css@3.4.8/lib/imports/inliner.js:157:12)
[01:58:24] 'deploy' errored after 5.77 s
[01:58:24] Error in plugin 'run-sequence'
Message:
    An error occured in task 'scripts-bundle'.
The command "gulp deploy" exited with 1.
Done. Your build exited with 1.
```

**Comment by justindujardin** [comment]
@madhukard thanks for reporting.  This should be fixed in 0.1.4, can you please confirm? Please reopen this if it's still an issue.
